#ifndef DRV_GPIO_H__
#define DRV_GPIO_H__

#include "hc32_ll.h"

#define LEDRUN_PORT			(GPIO_PORT_B)
#define LEDRUN_PIN			(GPIO_PIN_02)	
#define LEDERR_PORT			(GPIO_PORT_E)
#define LEDERR_PIN			(GPIO_PIN_07)
#define WTD_PORT			(GPIO_PORT_D)
#define WTD_PIN				(GPIO_PIN_03)
#define JY_K1_PORT			(GPIO_PORT_E)
#define JY_K1_PIN			(GPIO_PIN_04)
#define JY_K2_PORT			(GPIO_PORT_E)
#define JY_K2_PIN			(GPIO_PIN_02)
#define JY_K3_PORT			(GPIO_PORT_C)
#define JY_K3_PIN			(GPIO_PIN_13)
#define DI1_PORT			(GPIO_PORT_C)
#define DI1_PIN				(GPIO_PIN_09)
#define DI2_PORT			(GPIO_PORT_A)
#define DI2_PIN				(GPIO_PIN_09)
#define DI3_PORT			(GPIO_PORT_A)
#define DI3_PIN				(GPIO_PIN_11)
#define DI4_PORT			(GPIO_PORT_A)
#define DI4_PIN				(GPIO_PIN_15)
#define DI5_PORT			(GPIO_PORT_C)
#define DI5_PIN				(GPIO_PIN_11)
#define DI6_PORT			(GPIO_PORT_C)
#define DI6_PIN				(GPIO_PIN_12)
#define DI7_PORT			(GPIO_PORT_C)
#define DI7_PIN				(GPIO_PIN_07)
#define DI8_PORT			(GPIO_PORT_D)
#define DI8_PIN				(GPIO_PIN_15)
#define EVOUT_PORT			(GPIO_PORT_C)
#define EVOUT_PIN			(GPIO_PIN_06)
#define DO1_PORT			(GPIO_PORT_C)
#define DO1_PIN				(GPIO_PIN_08)
#define DO2_PORT			(GPIO_PORT_A)
#define DO2_PIN				(GPIO_PIN_08)
#define DO3_PORT			(GPIO_PORT_A)
#define DO3_PIN				(GPIO_PIN_10)
#define DO4_PORT			(GPIO_PORT_A)
#define DO4_PIN				(GPIO_PIN_12)
#define DO5_PORT			(GPIO_PORT_C)
#define DO5_PIN				(GPIO_PIN_10)
#define DO6_PORT			(GPIO_PORT_D)
#define DO6_PIN				(GPIO_PIN_00)
#define DO7_PORT			(GPIO_PORT_D)
#define DO7_PIN				(GPIO_PIN_01)
#define ADDR_PORT			(GPIO_PORT_D)
#define ADDR_PIN			(GPIO_PIN_02)
#define S_A_PORT			(GPIO_PORT_B)
#define S_A_PIN				(GPIO_PIN_06)		
#define S_B_PORT			(GPIO_PORT_B)
#define S_B_PIN				(GPIO_PIN_05)	
#define S_C_PORT			(GPIO_PORT_B)
#define S_C_PIN				(GPIO_PIN_04)	

#define I2C_WAKEUP_PORT		(GPIO_PORT_B)        
#define I2C_WAKEUP_PIN		(GPIO_PIN_03) 

#define VER_PORT0      (GPIO_PORT_E)
#define VER_PIN0       (GPIO_PIN_05)
#define VER_PORT1      (GPIO_PORT_E)
#define VER_PIN1       (GPIO_PIN_06)
#define LEDRUN_SET()		GPIO_SetPins(LEDRUN_PORT, LEDRUN_PIN)
#define LEDRUN_RST()		GPIO_ResetPins(LEDRUN_PORT, LEDRUN_PIN)
#define LEDRUN_TOGGLE()		GPIO_TogglePins(LEDRUN_PORT, LEDRUN_PIN)
#define LEDERR_SET()		GPIO_SetPins(LEDERR_PORT, LEDERR_PIN)
#define LEDERR_RST()		GPIO_ResetPins(LEDERR_PORT, LEDERR_PIN)
#define LEDERR_TOGGLE()		GPIO_TogglePins(LEDERR_PORT, LEDERR_PIN)
#define WTD_SET()			GPIO_SetPins(WTD_PORT, WTD_PIN)
#define WTD_RST()			GPIO_ResetPins(WTD_PORT, WTD_PIN)	
#define JY_K1_SET()			GPIO_SetPins(JY_K1_PORT, JY_K1_PIN)
#define JY_K1_RST()			GPIO_ResetPins(JY_K1_PORT, JY_K1_PIN)
#define JY_K2_SET()			GPIO_SetPins(JY_K2_PORT, JY_K2_PIN)
#define JY_K2_RST()			GPIO_ResetPins(JY_K2_PORT, JY_K2_PIN)
#define JY_K3_SET()			GPIO_SetPins(JY_K3_PORT, JY_K3_PIN)
#define JY_K3_RST()			GPIO_ResetPins(JY_K3_PORT, JY_K3_PIN)
#define EVOUT_SET()			GPIO_SetPins(EVOUT_PORT, EVOUT_PIN)
#define DO1_SET()			GPIO_SetPins(DO1_PORT, DO1_PIN)
#define DO2_SET()			GPIO_SetPins(DO2_PORT, DO2_PIN)
#define DO3_SET()			GPIO_SetPins(DO3_PORT, DO3_PIN)
#define DO4_SET()			GPIO_SetPins(DO4_PORT, DO4_PIN)
#define DO5_SET()			GPIO_SetPins(DO5_PORT, DO5_PIN)
#define DO6_SET()			GPIO_SetPins(DO6_PORT, DO6_PIN)
#define DO7_SET()			GPIO_SetPins(DO7_PORT, DO7_PIN)
#define ADDR_SET()			GPIO_SetPins(ADDR_PORT, ADDR_PIN)
#define EVOUT_RST()			GPIO_ResetPins(EVOUT_PORT, EVOUT_PIN)
#define DO1_RST()			GPIO_ResetPins(DO1_PORT, DO1_PIN)
#define DO2_RST()			GPIO_ResetPins(DO2_PORT, DO2_PIN)
#define DO3_RST()			GPIO_ResetPins(DO3_PORT, DO3_PIN)
#define DO4_RST()			GPIO_ResetPins(DO4_PORT, DO4_PIN)
#define DO5_RST()			GPIO_ResetPins(DO5_PORT, DO5_PIN)
#define DO6_RST()			GPIO_ResetPins(DO6_PORT, DO6_PIN)
#define DO7_RST()			GPIO_ResetPins(DO7_PORT, DO7_PIN)
#define ADDR_RST()			GPIO_ResetPins(ADDR_PORT, ADDR_PIN)
#define S_A_SET()			GPIO_SetPins(S_A_PORT, S_A_PIN)
#define S_A_RST()			GPIO_ResetPins(S_A_PORT, S_A_PIN)
#define S_B_SET()			GPIO_SetPins(S_B_PORT, S_B_PIN)
#define S_B_RST()			GPIO_ResetPins(S_B_PORT, S_B_PIN)
#define S_C_SET()			GPIO_SetPins(S_C_PORT, S_C_PIN)
#define S_C_RST()			GPIO_ResetPins(S_C_PORT, S_C_PIN)

void drv_gpio_init(void);
void WTD_Reset(void);
void reset_external_dog(void);


#endif
